function EnableMode(handles, EM)
global Enable_Mode
Enable_Mode = EM;
switch Enable_Mode
    case 1 % ПСП не рассчитана, производится установка параметров
        set(handles.sl_FR_CODE, 'Enable', 'off');
        set(handles.cb_Signal, 'Enable', 'on');
        set(handles.cb_Noise, 'Enable', 'on');
        set(handles.cb_jitter, 'Enable', 'on');
        set(handles.rb_YP4_Inf, 'Enable', 'on'); 
        set(handles.rb_YP4_2df, 'Enable', 'on'); 
        set(handles.rb_YP4_3, 'Enable', 'on'); 
        set(handles.rb_ADC_inf, 'Enable', 'on'); 
        set(handles.rb_ADC_1bit, 'Enable', 'on'); 
        set(handles.rb_SinCos_Inf, 'Enable', 'off'); 
        set(handles.rb_SinCos_4bita, 'Enable', 'off');   
        set(handles.reg1, 'Enable', 'on'); set(handles.reg2, 'Enable', 'on'); set(handles.reg3, 'Enable', 'on');
        set(handles.reg4, 'Enable', 'on'); set(handles.reg5, 'Enable', 'on'); set(handles.reg6, 'Enable', 'on');       
        set(handles.reg7, 'Enable', 'on'); set(handles.reg8, 'Enable', 'on'); set(handles.reg9, 'Enable', 'on');       
        set(handles.cb_RG1, 'Enable', 'on'); set(handles.cb_RG2, 'Enable', 'on'); set(handles.cb_RG3, 'Enable', 'on');
        set(handles.cb_RG4, 'Enable', 'on'); set(handles.cb_RG5, 'Enable', 'on'); set(handles.cb_RG6, 'Enable', 'on');       
        set(handles.cb_RG7, 'Enable', 'on'); set(handles.cb_RG8, 'Enable', 'on'); set(handles.cb_RG9, 'Enable', 'on');
        set(handles.pop_IQ, 'Enable', 'off');
        set(handles.but_CorrReset, 'Enable', 'off');    
        set(handles.but_OneClock, 'Enable', 'off');    
        set(handles.but_OnOffClock, 'Enable', 'off');   
        set(handles.but_CalcAll, 'Enable', 'on');        
    case 2 % Идёт расчет ПСП
        set(handles.sl_FR_CODE, 'Enable', 'off');
        set(handles.cb_Signal, 'Enable', 'off');
        set(handles.cb_Noise, 'Enable', 'off');
        set(handles.cb_jitter, 'Enable', 'off');
        set(handles.rb_YP4_Inf, 'Enable', 'off'); 
        set(handles.rb_YP4_2df, 'Enable', 'off'); 
        set(handles.rb_YP4_3, 'Enable', 'off'); 
        set(handles.rb_ADC_inf, 'Enable', 'off'); 
        set(handles.rb_ADC_1bit, 'Enable', 'off'); 
        set(handles.rb_SinCos_Inf, 'Enable', 'off'); 
        set(handles.rb_SinCos_4bita, 'Enable', 'off'); 
        set(handles.reg1, 'Enable', 'inactive'); set(handles.reg2, 'Enable', 'inactive'); set(handles.reg3, 'Enable', 'inactive');
        set(handles.reg4, 'Enable', 'inactive'); set(handles.reg5, 'Enable', 'inactive'); set(handles.reg6, 'Enable', 'inactive');       
        set(handles.reg7, 'Enable', 'inactive'); set(handles.reg8, 'Enable', 'inactive'); set(handles.reg9, 'Enable', 'inactive');       
        set(handles.cb_RG1, 'Enable', 'inactive'); set(handles.cb_RG2, 'Enable', 'inactive'); set(handles.cb_RG3, 'Enable', 'inactive');
        set(handles.cb_RG4, 'Enable', 'inactive'); set(handles.cb_RG5, 'Enable', 'inactive'); set(handles.cb_RG6, 'Enable', 'inactive');       
        set(handles.cb_RG7, 'Enable', 'inactive'); set(handles.cb_RG8, 'Enable', 'inactive'); set(handles.cb_RG9, 'Enable', 'inactive');         
        set(handles.pop_IQ, 'Enable', 'off');    
        set(handles.but_CorrReset, 'Enable', 'off');    
        set(handles.but_OneClock, 'Enable', 'off');    
        set(handles.but_OnOffClock, 'Enable', 'off');   
        set(handles.but_CalcAll, 'Enable', 'off');        
    case 3 % Идёт расчет по векторной модели
        set(handles.sl_FR_CODE, 'Enable', 'off');
        set(handles.cb_Signal, 'Enable', 'off');
        set(handles.cb_Noise, 'Enable', 'off');
        set(handles.cb_jitter, 'Enable', 'off');
        set(handles.rb_YP4_Inf, 'Enable', 'off'); 
        set(handles.rb_YP4_2df, 'Enable', 'off'); 
        set(handles.rb_YP4_3, 'Enable', 'off'); 
        set(handles.rb_ADC_inf, 'Enable', 'off'); 
        set(handles.rb_ADC_1bit, 'Enable', 'off'); 
        set(handles.rb_SinCos_Inf, 'Enable', 'off'); 
        set(handles.rb_SinCos_4bita, 'Enable', 'off'); 
        set(handles.reg1, 'Enable', 'inactive'); set(handles.reg2, 'Enable', 'inactive'); set(handles.reg3, 'Enable', 'inactive');
        set(handles.reg4, 'Enable', 'inactive'); set(handles.reg5, 'Enable', 'inactive'); set(handles.reg6, 'Enable', 'inactive');       
        set(handles.reg7, 'Enable', 'inactive'); set(handles.reg8, 'Enable', 'inactive'); set(handles.reg9, 'Enable', 'inactive');       
        set(handles.cb_RG1, 'Enable', 'inactive'); set(handles.cb_RG2, 'Enable', 'inactive'); set(handles.cb_RG3, 'Enable', 'inactive');
        set(handles.cb_RG4, 'Enable', 'inactive'); set(handles.cb_RG5, 'Enable', 'inactive'); set(handles.cb_RG6, 'Enable', 'inactive');       
        set(handles.cb_RG7, 'Enable', 'inactive'); set(handles.cb_RG8, 'Enable', 'inactive'); set(handles.cb_RG9, 'Enable', 'inactive');         
        set(handles.pop_IQ, 'Enable', 'off');    
        set(handles.but_CorrReset, 'Enable', 'off');    
        set(handles.but_OneClock, 'Enable', 'off');    
        set(handles.but_OnOffClock, 'Enable', 'off');   
        set(handles.but_CalcAll, 'Enable', 'off');        
    case 4 % ПСП рассчитана, расчеты по векторной модели завершены, возможна пауза тактовой модели
        set(handles.sl_FR_CODE, 'Enable', 'off');
        set(handles.cb_Signal, 'Enable', 'on');
        set(handles.cb_Noise, 'Enable', 'on');
        set(handles.cb_jitter, 'Enable', 'on');
        set(handles.rb_YP4_Inf, 'Enable', 'on'); 
        set(handles.rb_YP4_2df, 'Enable', 'on'); 
        set(handles.rb_YP4_3, 'Enable', 'on'); 
        set(handles.rb_ADC_inf, 'Enable', 'on'); 
        set(handles.rb_ADC_1bit, 'Enable', 'on'); 
        set(handles.rb_SinCos_Inf, 'Enable', 'on'); 
        set(handles.rb_SinCos_4bita, 'Enable', 'on'); 
        set(handles.reg1, 'Enable', 'on'); set(handles.reg2, 'Enable', 'on'); set(handles.reg3, 'Enable', 'on');
        set(handles.reg4, 'Enable', 'on'); set(handles.reg5, 'Enable', 'on'); set(handles.reg6, 'Enable', 'on');       
        set(handles.reg7, 'Enable', 'on'); set(handles.reg8, 'Enable', 'on'); set(handles.reg9, 'Enable', 'on');       
        set(handles.cb_RG1, 'Enable', 'on'); set(handles.cb_RG2, 'Enable', 'on'); set(handles.cb_RG3, 'Enable', 'on');
        set(handles.cb_RG4, 'Enable', 'on'); set(handles.cb_RG5, 'Enable', 'on'); set(handles.cb_RG6, 'Enable', 'on');       
        set(handles.cb_RG7, 'Enable', 'on'); set(handles.cb_RG8, 'Enable', 'on'); set(handles.cb_RG9, 'Enable', 'on');           
        set(handles.pop_IQ, 'Enable', 'on'); 
        set(handles.but_CorrReset, 'Enable', 'on');    
        set(handles.but_OneClock, 'Enable', 'on');    
        set(handles.but_OnOffClock, 'Enable', 'on'); 
        set(handles.but_CalcAll, 'Enable', 'off');        
    case 5 % ПСП рассчитана, запущен один такт пошаговой модели 
        set(handles.sl_FR_CODE, 'Enable', 'off');        
        set(handles.cb_Signal, 'Enable', 'off');        
        set(handles.cb_Noise, 'Enable', 'off');
        set(handles.cb_jitter, 'Enable', 'off');
        set(handles.rb_YP4_Inf, 'Enable', 'off'); 
        set(handles.rb_YP4_2df, 'Enable', 'off'); 
        set(handles.rb_YP4_3, 'Enable', 'off'); 
        set(handles.rb_ADC_inf, 'Enable', 'off'); 
        set(handles.rb_ADC_1bit, 'Enable', 'off'); 
        set(handles.rb_SinCos_Inf, 'Enable', 'off'); 
        set(handles.rb_SinCos_4bita, 'Enable', 'off'); 
        set(handles.reg1, 'Enable', 'inactive'); set(handles.reg2, 'Enable', 'inactive'); set(handles.reg3, 'Enable', 'inactive');
        set(handles.reg4, 'Enable', 'inactive'); set(handles.reg5, 'Enable', 'inactive'); set(handles.reg6, 'Enable', 'inactive');       
        set(handles.reg7, 'Enable', 'inactive'); set(handles.reg8, 'Enable', 'inactive'); set(handles.reg9, 'Enable', 'inactive');       
        set(handles.cb_RG1, 'Enable', 'inactive'); set(handles.cb_RG2, 'Enable', 'inactive'); set(handles.cb_RG3, 'Enable', 'inactive');
        set(handles.cb_RG4, 'Enable', 'inactive'); set(handles.cb_RG5, 'Enable', 'inactive'); set(handles.cb_RG6, 'Enable', 'inactive');       
        set(handles.cb_RG7, 'Enable', 'inactive'); set(handles.cb_RG8, 'Enable', 'inactive'); set(handles.cb_RG9, 'Enable', 'inactive');   
        set(handles.pop_IQ, 'Enable', 'on');   
        set(handles.but_CorrReset, 'Enable', 'off');    
        set(handles.but_OneClock, 'Enable', 'off');    
        set(handles.but_OnOffClock, 'Enable', 'off');  
        set(handles.but_CalcAll, 'Enable', 'off');        
    case 6 % ПСП рассчитана, запущена последовательность тактов пошаговой модели 
        set(handles.sl_FR_CODE, 'Enable', 'off');        
        set(handles.cb_Signal, 'Enable', 'off');        
        set(handles.cb_Noise, 'Enable', 'off');
        set(handles.cb_jitter, 'Enable', 'off');
        set(handles.rb_YP4_Inf, 'Enable', 'off'); 
        set(handles.rb_YP4_2df, 'Enable', 'off'); 
        set(handles.rb_YP4_3, 'Enable', 'off'); 
        set(handles.rb_ADC_inf, 'Enable', 'off'); 
        set(handles.rb_ADC_1bit, 'Enable', 'off'); 
        set(handles.rb_SinCos_Inf, 'Enable', 'off'); 
        set(handles.rb_SinCos_4bita, 'Enable', 'off'); 
        set(handles.reg1, 'Enable', 'inactive'); set(handles.reg2, 'Enable', 'inactive'); set(handles.reg3, 'Enable', 'inactive');
        set(handles.reg4, 'Enable', 'inactive'); set(handles.reg5, 'Enable', 'inactive'); set(handles.reg6, 'Enable', 'inactive');       
        set(handles.reg7, 'Enable', 'inactive'); set(handles.reg8, 'Enable', 'inactive'); set(handles.reg9, 'Enable', 'inactive');       
        set(handles.cb_RG1, 'Enable', 'inactive'); set(handles.cb_RG2, 'Enable', 'inactive'); set(handles.cb_RG3, 'Enable', 'inactive');
        set(handles.cb_RG4, 'Enable', 'inactive'); set(handles.cb_RG5, 'Enable', 'inactive'); set(handles.cb_RG6, 'Enable', 'inactive');       
        set(handles.cb_RG7, 'Enable', 'inactive'); set(handles.cb_RG8, 'Enable', 'inactive'); set(handles.cb_RG9, 'Enable', 'inactive');   
        set(handles.pop_IQ, 'Enable', 'on');   
        set(handles.but_CorrReset, 'Enable', 'off');    
        set(handles.but_OneClock, 'Enable', 'off');    
        set(handles.but_OnOffClock, 'Enable', 'on');               
        set(handles.but_CalcAll, 'Enable', 'off');
end